apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.db.configmap }}
  namespace: {{ .Values.namespace }}
data:
  POSTGRES_HOST: {{ .Values.db.serviceName }}
  POSTGRES_DB: {{ .Values.db.databaseName }}
  POSTGRES_PORT: "{{ .Values.db.port }}"
  POSTGRES_SSL: "{{ .Values.db.ssl }}"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.backend.configmap }}
  namespace: {{ .Values.namespace }}
data:
  SERVER_NAME: {{- template "serverName" }}
  SERVER_HOST: "http://localhost"
  BACKEND_CORS_ORIGINS: '["{{ .Values.appProtocol}}://{{ .Values.appDomain }}"]'
