{{- if eq .Values.deployType "DEV" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.passwordSecret.name }}
  namespace: {{ .Values.namespace }}
type: generic
data:
  password: {{ .Values.db.passwordSecret.value }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.db.usernameSecret.name }}
  namespace: {{ .Values.namespace }}
type: generic
data:
  username: {{ .Values.db.usernameSecret.value }}
---
{{- else if eq .Values.deployType "PROD"}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.backend.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secretStore.userAssignedIdentityID }}
    tenantID: {{ .Values.secretStore.tenantId }}
    keyvaultName: {{ .Values.secretStore.name }}
    objects: |
      array:
        - |
          objectName: {{ .Values.tlsSecret }}
          objectType: secret
        - |
          objectName: {{ .Values.db.usernameSecret.name }}
          objectType: secret
          objectVersion: ""
        - |
          objectName: {{ .Values.db.passwordSecret.name }}
          objectType: secret
          objectVersion: ""
  secretObjects:
    - data:
      - key: tls.key
        objectName: {{ .Values.tlsSecret }}
      - key: tls.crt
        objectName: {{ .Values.tlsSecret }}
      secretName: {{ .Values.tlsSecret }}
      type: kubernetes.io/tls
    - data:
        - key: secret
          objectName: {{ .Values.db.usernameSecret.name }}
      secretName: {{ .Values.db.usernameSecret.name }}
      type: generic
    - data:
        - key: secret
          objectName: {{ .Values.db.passwordSecret.name }}
      secretName: {{ .Values.db.passwordSecret.name }}
      type: generic
# Sources:
# https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access
# https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#validate-the-secrets
# https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver
{{- end }}